[{head:"id",value:false},
                    {head:"satellite", value:false},
                    {head:"type", value:false},
                    {head:"insert_request", value:false},
                    {head:"work_order_id",value:false},
                    {head:"order_id",value:false},
                    {head:"pr_id",value:false},
                    {head:"ar_counter",value:false},
                    {head:"dtos_id",value:false},
                    {head:"acq_date",value:false},
                    {head:"start_time",value:false},
                    {head:"stop_time",value:false},
                    {head:"sensor_mode", value:false},
                    {head:"level",value:false},
                    {head:"format",value:false},
                    {head:"direction",value:false},
                    {head:"angle",value:false},
                    {head:"polarization",value:false},
                    {head:"aoi_tl_n",value:false},
                    {head:"aoi_tl_e",value:false},
                    {head:"aoi_tr_n",value:false},
                    {head:"aoi_tr_e",value:false},
                    {head:"aoi_br_n",value:false},
                    {head:"aoi_br_e",value:false},
                    {head:"aoi_bl_n",value:false},
                    {head:"aoi_bl_e",value:false},
                    {head:"area",value:false},
                    {head:"waiting",value:false},
                    {head:"description",value:false},
                    {head:"remark",value:false},
                    {head:"operator",value:false},
                    {head:"qty",value:false},
                    {head:"package",value:false},
                    {head:"troble_ticket",value:false}
                ]