export const TableHead = {
        satellite : "",
        type : "",
        insert_request : "",
        work_order_id : "",
        order_id : "",
        pr_id : "",
        ar_counter : "",
        dtos_id : "",
        acq_date : "",
        start_time : "",
        stop_time : "",
        sensor_mode : "",
        level : "",
        format : "",
        direction : "",
        angle : '',
        polarization : '',
        aoi_tl_n : '',
        aoi_tl_e : '',
        aoi_tr_n : '',
        aoi_tr_e : '',
        aoi_br_n : '',
        aoi_br_e : '',
        aoi_bl_n : '',
        aoi_bl_e : '',
        area : '',
        status : '',
        description : '',
        remark : '',
        operator : '',
        qty : '',
        package : '',


}